Refs #35308 - Propagate the new registered name to more places (#744)
* Refs #35308 - Propagate the new registered name to more places

Without this, running a job would fail with
NoMethodError: undefined method `host_id=' for ["SSH", "Script"]:Array

* Refs #35308 - Allow different proxy feature and registered provider names

(cherry picked from commit f5f3172e6e1a2ad9cc1bf0f759a3ae2257d54014)